on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-2-l2d2.de
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://kima.rrze.uni-erlangen.de/proj/websource/docs/kooperationen/www.l2d2.de/websource/KIT
        ftp-username: ends02wm
        ftp-password: ${{ secrets.FTPZUGANG }}
